name: hc_05
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_background_geolocation: ^4.16.9
  flutter_bluetooth_serial: ^0.4.0
  flutter_blue_plus: ^1.35.3
  geolocator: ^9.0.0
  osrm: ^0.0.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  http: ^1.3.0
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0
  osm_nominatim: ^3.0.1
  mockito: ^5.4.0
  mocktail: ^0.3.0
  flutter_launcher_icons: "^0.14.3"
  build_runner: ^2.4.15
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_background: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "images/smart_turn.png"