# Generated by Django 5.0.1 on 2024-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_times_remove_vetschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
