# Generated by Django 5.0.1 on 2024-02-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_orgprofile_type_userprofile_type_vetprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgprofile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vetprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.orgprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vet_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.vetprofile'),
        ),
    ]
