# Generated by Django 5.0.1 on 2024-02-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_orgprofile_type_remove_vetprofile_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='org_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vet_profile',
        ),
    ]
