# Generated by Django 5.0.1 on 2024-02-13 14:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_remove_userprofile_org_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetschedule',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='times',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='VetScheduleCollector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vet_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.vetprofile')),
                ('vet_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.vetschedule')),
            ],
        ),
    ]
