# Generated by Django 5.0.1 on 2024-02-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_vetschedule_date_alter_times_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Times',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='name',
            new_name='time',
        ),
    ]
