# Generated by Django 5.0.1 on 2024-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_rename_times_time_rename_name_time_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetschedule',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
