# Generated by Django 5.0.1 on 2024-02-13 16:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_vetschedule_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(default='', max_length=255)),
                ('breed', models.CharField(default='', max_length=255)),
                ('location_found', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='StrayAnimal',
        ),
    ]
