# Generated by Django 5.0.1 on 2024-02-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_remove_vetschedule_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetschedule',
            name='date',
            field=models.DateField(default='', verbose_name='Date'),
        ),
    ]
