# Generated by Django 5.0.1 on 2024-02-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_alter_vetschedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='time',
        ),
        migrations.RemoveField(
            model_name='vetschedulecollector',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='vetschedulecollector',
            name='report',
        ),
        migrations.AddField(
            model_name='time',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='time',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.animal'),
            preserve_default=False,
        ),
    ]
