# Generated by Django 5.0.1 on 2024-02-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_remove_time_booked_remove_time_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetschedule',
            name='times',
        ),
        migrations.AddField(
            model_name='vetschedule',
            name='time',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user_profile.time'),
            preserve_default=False,
        ),
    ]
