# Generated by Django 5.0.1 on 2024-02-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_remove_vetschedule_times_vetschedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='time',
            field=models.CharField(default=''),
        ),
    ]
