# Generated by Django 5.0.1 on 2024-02-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_animal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetschedule',
            name='vet_profile',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='user_profile.vetprofile'),
            preserve_default=False,
        ),
    ]
