# Generated by Django 5.0.1 on 2024-02-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_vetschedule_vet_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Report',
        ),
    ]
