# Generated by Django 5.0.1 on 2024-02-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_rename_animal_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
    ]
