# Generated by Django 5.0.1 on 2024-02-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_remove_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetschedule',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vetschedule',
            name='report',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='user_profile.report'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VetScheduleCollector',
        ),
    ]
