# Generated by Django 5.0.1 on 2024-02-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0023_vetschedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetschedule',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.report'),
        ),
    ]
