# Generated by Django 5.0.1 on 2024-02-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_alter_vetschedule_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetschedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
