# Generated by Django 5.0.1 on 2024-02-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0025_alter_vetschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
