# Generated by Django 5.0.1 on 2024-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_vetprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
