
//Auth Dispatch States
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL= 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL= 'LOGOUT_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL= 'AUTHENTICATED_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL= 'DELETE_USER_FAIL';

//Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAIL= 'LOAD_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL= 'UPDATE_USER_PROFILE_FAIL';
export const CHECK_PROFILE_SUCCESS = 'CHECK_USER_PROFILE_SUCCESS';
export const CHECK_USER_PROFILE_FAIL= 'CHECK_USER_PROFILE_FAIL';

//Vet Dispatch States

export const UPDATE_VET_SCHEDULE_SUCCESS = 'UPDATE_VET_SCHEDULE_SUCCESS';
export const UPDATE_VET_SCHEDULE_FAIL= 'UPDATE_VET_SCHEDULE_FAIL';
export const UPDATE_VET_PROFILE_SUCCESS = 'UPDATE_VET_PROFILE_SUCCESS';
export const UPDATE_VET_PROFILE_FAIL= 'UPDATE_VET_PROFILE_FAIL';
export const LOAD_VET_SCHEDULE_SUCCESS = 'LOAD_VET_SCHEDULE_SUCCESS';
export const LOAD_VET_SCHEDULE_FAIL= 'LOAD_VET_SCHEDULE_FAIL';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_FAIL= 'DELETE_SCHEDULE_FAIL';
export const LOAD_VET_PROFILE_SUCCESS = 'LOAD_VET_PROFILE_SUCCESS';
export const NEW_SCHEDULE_FAIL= 'NEW_SCHEDULE_FAIL';
export const NEW_SCHEDULE_SUCCESS = 'NEW_SCHEDULE_SUCCESS';
export const MAKE_BOOKING_FAIL= 'MAKE_BOOKING_FAIL';
export const MAKE_BOOKING_SUCCESS = 'MAKE_BOOKING_SUCCESS';
export const LOAD_VET_SCHEDULE_USER_SUCCESS = 'LOAD_VET_SCHEDULE_USER_SUCCESS';
export const LOAD_VET_SCHEDULE_USER_FAIL= 'LOAD_VET_SCHEDULE_USER_FAIL';
export const LOAD_ALL_BOOKED_SUCCESS = 'LOAD_ALL_BOOKED_SUCCESS';
export const LOAD_ALL_BOOKED_FAIL= 'LOAD_ALL_BOOKED_FAIL';
export const LOAD_USER_BOOKED_SUCCESS = 'LOAD_USER_BOOKED_SUCCESS';
export const LOAD_USER_BOOKED_FAIL= 'LOAD_USER_BOOKED_FAIL';


// Time Dispatch States
export const LOAD_FREE_TIME_SUCCESS = 'LOAD_FREE_TIME_SUCCESS';
export const LOAD_FREE_TIME_FAIL= 'LOAD_FREE_TIME_FAIL';

// Org Dispatch States

export const LOAD_ORG_PROFILE_SUCCESS = 'LOAD_ORG_PROFILE_SUCCESS';
export const LOAD_ORG_PROFILE_FAIL = 'LOAD_ORG_PROFILE_FAIL';
export const UPDATE_ORG_PROFILE_SUCCESS = 'UPDATE_ORG_PROFILE_SUCCESS';
export const UPDATE_ORG_PROFILE_FAIL= 'UPDATE_ORG_PROFILE_FAIL';
export const MAKE_REPORT_FAIL= 'MAKE_REPORT_FAIL';
export const MAKE_REPORT_SUCCESS = 'MAKE_REPORT_SUCCESS';
export const LOAD_ORG_REPORTS_SUCCESS = 'LOAD_ORG_REPORTS_SUCCESS';
export const LOAD_ORG_REPORTS_FAIL= 'LOAD_ORG_REPORTS_FAIL';
export const LOAD_USER_REPORTS_SUCCESS = 'LOAD_USER_REPORTS_SUCCESS';
export const LOAD_USER_REPORTS_FAIL= 'LOAD_USER_REPORTS_FAIL';
